export const OPEN_DRAWER = 'OPEN_DRAWER'
export const CLOSE_DRAWER = 'CLOSE_DRAWER'
export const OPEN_FORM_EDIT_PROJECT = 'OPEN_FORM_EDIT_PROJECT'
export const OPEN_FORM_CREATE_TASK = 'OPEN_FORM_CREATE_TASK'